baseURL = "https://keanu73.net"
languageCode = "en-gb"
title = "Keanu C."
googleAnalytics = "UA-53637883-3"

[menu]
  [[menu.header]]
    name = "mail"
    weight = 0
    url = "/mail"

[params]
  title = "Keanu C."
  description = "You have 1 unread message."
  images = ["aiden.png"]
  
  GithubID = "Keanu73"
  TwitterID = "Keanu73RBLX"
  RedditID = "Keanu73"
  Email = "keanu@keanu73.net"
  KeybaseID = "keanu73"
  Name = "Keanu C."
  HeaderUsername = "keanu73"
  HeaderHostname = "zion"
  About = "Hello there. I'm Keanu, and I'm a young programmer with a lot of time on their hands. I spend most of my days either pre-meditating code and writing it. I also have a keen interest in flight simulation and FPS games, and on top of that I also control on VATSIM in my spare time. I work on lots of different projects for myself and all sorts of people - if you want to see some of them, you can check out my GitHub profile above."
  ProfilePicture = "/aiden.png"
  Favicon = "/aiden.png"